In [14]:
import numpy as np
import torch
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
z
# x

tensor([[-0.7039,  0.7159, -0.8558,  1.2056,  1.9943,  0.3601,  1.8999, -0.4122],
        [-0.4122,  1.4688,  0.8050, -0.5271, -1.2572,  1.2877, -0.3825,  1.3130]])

In [15]:
x = torch.randn(1)
x


tensor([0.1595])

In [32]:
# dir(x)

In [31]:
x.data


tensor([0.1595])

In [18]:
x.grad

In [20]:
x.item()

0.15945971012115479

In [23]:
z.transpose(1,0)

tensor([[-0.7039, -0.4122],
        [ 0.7159,  1.4688],
        [-0.8558,  0.8050],
        [ 1.2056, -0.5271],
        [ 1.9943, -1.2572],
        [ 0.3601,  1.2877],
        [ 1.8999, -0.3825],
        [-0.4122,  1.3130]])

In [24]:
a = torch.ones(5)
a


tensor([1., 1., 1., 1., 1.])

In [25]:
b = a.numpy()
b = torch.from_numpy(a)

array([1., 1., 1., 1., 1.], dtype=float32)

In [33]:
# dir(b)
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu",torch.double))
    y.to("cpu").data.numpy
    y.cpu().data.numpy()
else:
    print("False")



False


In [14]:
# 模型cuda
# model = model.cuda()
# numpy 实现两层神经网络
"""
h = w1 *  x + b1
a = max(0,h)
y_hat = w2 * a +  b2
numpy 实现前项传播
loss  实现反向传播
"""
#
import numpy as np
N, D_in, H, D_out = 64,1000,100,10
x = np.random.randn(N, D_in)
y = np.random.randn(N, D_out)

w1 = np.random.randn(D_in,H)
w2 = np.random.randn(H,D_out)

learning_rate = 1e-6

for t in range(20):
    h = x.dot(w1)
    h_relu = np.maximum(h,0)
    y_pred = h_relu.dot(w2)

    #compute loss
    loss = np.sqrt((y_pred-y)**2).sum()
    print(t,"  ",loss)

    # bp
    # compute grad
    grad_y_pred = 2.0 * ( y_pred - y)
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h<0] = 0
    grad_w1 = x.T.dot(grad_h)

    # 更新权重
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

0    110598.83212851276
1    103421.27731818029
2    111052.97557799023
3    114460.48868692169
4    114587.37565457495
5    101063.35135368857
6    82199.59207084303
7    60147.13262567447
8    43722.10196876158
9    31757.14369461876
10    24685.552281638273
11    20112.144792350962
12    17234.827347441817
13    15275.770427447638
14    13866.52183897293
15    12663.621506661333
16    11734.328840211505
17    10836.424883344904
18    10117.638273358403
19    9422.658859502613


In [70]:
# h = x.dot(w1)
# h_relu = np.maximum(h,0)
# y_pred = h_relu.dot(w2)
# y_pred - y

In [15]:
# 手动自己下降
import numpy as np
import torch

N, D_in, H, D_out = 64,1000,100,10
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

w1 = torch.randn(D_in,H)
w2 = torch.randn(H,D_out)

learning_rate = 1e-6

for t in range(20):
    h = x.mm(w1)
    # min max  控制区间
    h_relu = h.clamp(min=0)
    y_pred = h_relu.mm(w2)

    #compute loss
    loss = torch.sqrt((y_pred-y).pow(2)).sum().item()
    print(t,"  ",loss)

    # bp
    # compute grad
    grad_y_pred = 2.0 * ( y_pred - y)
    grad_w2 = h_relu.t().mm(grad_y_pred)
    grad_h_relu = grad_y_pred.mm(w2.t())
    grad_h = grad_h_relu.clone()
    grad_h[h<0] = 0
    grad_w1 = x.t().mm(grad_h)

    # 更新权重
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

0    104631.9609375
1    98196.2578125
2    96037.1875
3    92723.34375
4    86135.625
5    74664.828125
6    62014.515625
7    49469.94140625
8    39304.8515625
9    31815.8203125
10    25909.787109375
11    22173.203125
12    19067.80078125
13    16953.587890625
14    15268.1376953125
15    13934.2861328125
16    12858.3115234375
17    11878.064453125
18    11074.08984375
19    10309.806640625


In [20]:
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

y = w*x + b

y.backward()
w.grad

tensor(1.)

In [73]:
import numpy as np
import torch

N, D_in, H, D_out = 64,1000,100,10
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

w1 = torch.randn(D_in,H, requires_grad=True)
w2 = torch.randn(H,D_out, requires_grad=True)

learning_rate = 1e-6

for t in range(5000):
    # h = x.mm(w1)
    # # min max  控制区间
    # h_relu = h.clamp(min=0)
    # y_pred = h_relu.mm(w2)

    y_pred = x.mm(w1).clamp(min=0).mm(w2)

    #compute loss
    loss = (y_pred-y).pow(2).sum()
    if t % 500 == 0:
        print(t,"  ",loss.item())

    loss.backward()
    # bp
    # compute grad
    # grad_y_pred = 2.0 * ( y_pred - y)
    # grad_w2 = h_relu.t().mm(grad_y_pred)
    # grad_h_relu = grad_y_pred.mm(w2.t())
    # grad_h = grad_h_relu.clone()
    # grad_h[h<0] = 0
    # grad_w1 = x.t().mm(grad_h)

    # 更新权重
    # w1.data -= learning_rate * grad_w1.data
    # w2.data -= learning_rate * grad_w2.data
    with torch.no_grad():
        w1.data -= learning_rate * w1.grad.data
        w2.data -= learning_rate * w2.grad.data
        w1.grad.zero_()
        w2.grad.zero_()

0    29708336.0
500    0.01877054199576378
1000    3.282770558143966e-05
1500    8.45683734951308e-06
2000    4.567688392853597e-06
2500    2.9773877940897364e-06
3000    2.2134017854114063e-06
3500    1.7076991980502498e-06
4000    1.3651498420585995e-06
4500    1.1144190921186237e-06


In [74]:
y_pred = x.mm(w1).clamp(min=0).mm(w2)
(y - y_pred)[1]


tensor([ 4.8906e-05,  3.6955e-06,  1.0848e-05,  2.0280e-05, -1.9133e-05,
         1.8001e-05, -3.7074e-05,  3.1590e-06, -1.2994e-05,  1.9550e-05],
       grad_fn=<SelectBackward0>)

In [91]:
import torch
import torch.nn as nn

N, D_in, H, D_out = 64,1000,100,10
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

# w1 = torch.randn(D_in,H, requires_grad=True)
# w2 = torch.randn(H,D_out, requires_grad=True)

model = torch.nn.Sequential(
    torch.nn.Linear(D_in,H,bias=False),
    torch.nn.ReLU(),
    torch.nn.Linear(H,D_out,bias=False),
)

# 初始化
torch.nn.init.normal_(model[0].weight)
torch.nn.init.normal_(model[2].weight)
# model.cuda()

# learning_rate = 1e-4
# optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

learning_rate = 1e-6
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

loss_fn = nn.MSELoss(reduction='sum')


for t in range(500):

    y_pred = model(x)

    #compute loss
    # loss = (y_pred-y).pow(2).sum()
    loss = loss_fn(y_pred,y)
    if t % 50 == 0:
        print(t,"  ",loss.item())

    optimizer.zero_grad()
    loss.backward()

    # with torch.no_grad():
    #     for param in model.parameters():
    #         param -= learning_rate * param.grad
    # # model.zero_grad()
    optimizer.step()

0    32411706.0
50    11973.3896484375
100    504.5872802734375
150    39.74904251098633
200    3.8742401599884033
250    0.41466742753982544
300    0.04683134704828262
350    0.005689364392310381
400    0.0009358379757031798
450    0.0002564187743701041


In [85]:
# model[0]

In [95]:
import torch
import torch.nn as nn

N, D_in, H, D_out = 64,1000,100,10
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

# model = torch.nn.Sequential(
#     torch.nn.Linear(D_in,H,bias=False),
#     torch.nn.ReLU(),
#     torch.nn.Linear(H,D_out,bias=False),
# )

class TWOLayerNet(nn.Module):
    def __init__(self, D_in, H, D_out):
        super(TWOLayerNet, self).__init__()
        self.linear1 = torch.nn.Linear(D_in, H, bias=False)
        self.linear2 = torch.nn.Linear(H, D_out,bias=False)

    def forward(self,x):
        y_pred = self.linear2(self.linear1(x).clamp(min=0))
        return y_pred

model = TWOLayerNet(D_in, H, D_out)

# 初始化
# torch.nn.init.normal_(model[0].weight)
# torch.nn.init.normal_(model[2].weight)

learning_rate = 1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

loss_fn = nn.MSELoss(reduction='sum')


for t in range(500):

    y_pred = model(x)

    loss = loss_fn(y_pred,y)
    if t % 50 == 0:
        print(t,"  ",loss.item())

    optimizer.zero_grad()
    loss.backward()

    optimizer.step()


0    692.6516723632812
50    213.892822265625
100    54.61441421508789
150    9.1212739944458
200    0.8840866088867188
250    0.05116650462150574
300    0.0025561493821442127
350    0.00012613499711733311
400    5.318761395756155e-06
450    1.6408733927164576e-07
