In [5]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
from pandas import DataFrame as df

data = [[-1,2], [-0.5,6], [0,10], [1,18]]


In [6]:
df(data)

0   1
0 -1.0   2
1 -0.5   6
2  0.0  10
3  1.0  18

In [9]:
scaler = MinMaxScaler()
scaler = scaler.fit(data)
result = scaler.transform(data)

In [10]:
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [11]:
scaler.inverse_transform(result)


array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [12]:
# 调用 MinMaxScaler ，将数据归一化到 [0,1] 之外的区间
scaler = MinMaxScaler(feature_range=[5,10])
result = scaler.fit_transform(data)
result

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [17]:
from sklearn.preprocessing import StandardScaler
data = [[-1,2], [-0.5,6], [0,10], [1,18]]
scaler = StandardScaler()
scaler.fit(data)
scaler.mean_


array([-0.125,  9.   ])

In [18]:
scaler.var_

array([ 0.546875, 35.      ])

In [19]:
x_std = scaler.transform(data)



In [20]:
x_std.mean()


0.0

In [21]:
x_std.std()

1.0

In [22]:
x_std


array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [25]:
data = [[-1,2], [-0.5,6], [0,10], [1,18]]

x_std = scaler.transform(data)
scaler.inverse_transform(x_std)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [26]:
# 归一化  对异常值敏感
# 标准化

In [28]:
import pandas as pd
data = pd.read_csv(r"data/Narrativedata.csv", index_col=0)
data.head()

Age     Sex Embarked Survived
0  22.0    male        S       No
1  38.0  female        C      Yes
2  26.0  female        S      Yes
3  35.0  female        S      Yes
4  35.0    male        S       No

In [29]:
# from sklearn import
data.info()


<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       714 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [34]:
Age = data.loc[:,'Age'].values.reshape(-1,1)
# 输入为2维

In [63]:
# Age
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(strategy='mean')
imp_median = SimpleImputer(strategy='median')
imp_0 = SimpleImputer(strategy='constant', fill_value=0)
# imp_0 = imp_0.fit(Age)

In [64]:
imp_mean = imp_mean.fit_transform(Age)
imp_median = imp_median.fit_transform(Age)
imp_0 = imp_0.fit_transform(Age)

In [65]:
imp_mean[:20]

array([[22.        ],
       [38.        ],
       [26.        ],
       [35.        ],
       [35.        ],
       [29.69911765],
       [54.        ],
       [ 2.        ],
       [27.        ],
       [14.        ],
       [ 4.        ],
       [58.        ],
       [20.        ],
       [39.        ],
       [14.        ],
       [55.        ],
       [ 2.        ],
       [29.69911765],
       [31.        ],
       [29.69911765]])

In [66]:
imp_median[:20]

array([[22.],
       [38.],
       [26.],
       [35.],
       [35.],
       [28.],
       [54.],
       [ 2.],
       [27.],
       [14.],
       [ 4.],
       [58.],
       [20.],
       [39.],
       [14.],
       [55.],
       [ 2.],
       [28.],
       [31.],
       [28.]])

In [68]:
data.loc[:,"Age"] = imp_median

In [69]:
data.info()


<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       891 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [72]:
Embarked = data.loc[:, "Embarked"].values.reshape(-1,1)
imp_mode = SimpleImputer(strategy = "most_frequent")
data.loc[:, "Embarked"] = imp_mode.fit_transform(Embarked)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       891 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  891 non-null    object 
 3   Survived  891 non-null    object 
 4   Embark    891 non-null    object 
dtypes: float64(1), object(4)
memory usage: 41.8+ KB


In [73]:
data.dropna(axis=0, inplace=True)

In [74]:
data.head()


Age     Sex Embarked Survived Embark
0  22.0    male        S       No      S
1  38.0  female        C      Yes      C
2  26.0  female        S      Yes      S
3  35.0  female        S      Yes      S
4  35.0    male        S       No      S

In [94]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

y = data.iloc[:,-2]
le = LabelEncoder()
le = le.fit(y)
label = le.transform(y)
# label

In [93]:
# data.loc[:,-1]
# le.classes_

array([0, 1, 2])

In [96]:
# le.inverse_transform(label)

In [95]:
data.iloc[:, -2] = label


In [92]:
# data

In [88]:
data_ = data.copy()
data_.iloc[:, 1:-1] = OrdinalEncoder().fit_transform(data_.iloc[:, 1:-1])

In [91]:
data_.head(10)

Age  Sex  Embarked  Survived Embark
0  22.0  1.0       2.0       0.0      S
1  38.0  0.0       0.0       2.0      C
2  26.0  0.0       2.0       2.0      S
3  35.0  0.0       2.0       2.0      S
4  35.0  1.0       2.0       0.0      S
5  28.0  1.0       1.0       0.0      Q
6  54.0  1.0       2.0       0.0      S
7   2.0  1.0       2.0       0.0      S
8  27.0  0.0       2.0       2.0      S
9  14.0  0.0       0.0       2.0      C

In [ ]:
# one-hot 编码

